live_config_reload = true

import = [
    "~/.config/alacritty/themes/themes/onedark.toml"
]

[env]
TERM = "alacritty"

[font]
size = 16.0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[window]
startup_mode = "Maximized"
opacity = 0.6
blur = true

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"
